# Generated by Django 2.2.1 on 2019-06-07 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pagina_conteudo', to='scrapy.Conteudo')),
            ],
        ),
    ]
