# Generated by Django 2.2.1 on 2019-06-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='palavra',
            field=models.CharField(max_length=100),
        ),
    ]
