# Generated by Django 2.1.9 on 2019-06-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0002_auto_20190611_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
